lists/urls.py
from django.conf.urls import url
from lists import views
urlpatterns = [
    url(r'^(\d+)/$', views.view_list, name='view_list'),
    url(r'^new$', views.new_list, name='new_list'),
    #url(r'^admin/', admin.site.urls),
]

pomodoro_web/urls.py
from django.conf.urls import url, include

from lists import views as lists_views

urlpatterns = [
    url(r'^$', lists_views.home_page, name='home'),
    url(r'^lists/', include('lists.urls')),
    # url(r'^admin/', admin.site.urls),
]

accounts/models.py
from django.db import models

# Create your models here.

lists/models.py
from django.core.urlresolvers import reverse
from django.db import models


class List(models.Model):
    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])


class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None)

    class Meta:
        ordering = ('id',)
        unique_together = ('list', 'text')

    def __str__(self):
        return self.text

tasks/models.py
from django.db import models
from django.utils import timezone

class Task(models.Model):
	title = models.TextField(default='')
	created_date = models.DateTimeField(default=timezone.now)

lists/forms.py
from django import forms
from django.core.exceptions import ValidationError

from lists.models import Item

EMPTY_LIST_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "이미 리스트에 해당 아이템이 있습니다"


class ItemForm(forms.models.ModelForm):
    class Meta:
        model = Item
        fields = ('text',)
        widgets = {
            'text': forms.fields.TextInput(attrs={
                'placeholder': '작업 아이템 입력',
                'class': 'form-control input-lg',
            }),
        }
        error_messages = {
            'text': {'required': EMPTY_LIST_ERROR}
        }

    def save(self, for_list):
        self.instance.list = for_list
        return super().save()


class ExistingListItemForm(ItemForm):
    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def save(self):
        return forms.models.ModelForm.save(self)

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

accounts/views.py
from django.shortcuts import render

# Create your views here.

lists/views.py
from django.shortcuts import render, redirect

from lists.forms import ItemForm, ExistingListItemForm
from lists.models import List


def home_page(request):
    return render(request, 'home.html', {'form': ItemForm()})


def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=list_)
    if request.method == 'POST':
        form = ExistingListItemForm(for_list=list_,data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(list_)
    return render(request, 'list.html', {'list': list_, 'form': form})


def new_list(request):
    form = ItemForm(data=request.POST)
    if form.is_valid():
        list_ = List.objects.create()
        form.save(for_list=list_)
        return redirect(list_)
    else:
        return render(request, 'home.html', {"form": form})

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Pomodoro web</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="/static/base.css" rel="stylesheet" media="screen">
</head>
<body>
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <a class="navbar-brand" href="/">Pomodoro web</a>
        <a class="btn navbar-btn navbar-right" id="id_login" href="#">로그인</a>
    </nav>
    <div class="row">
        <div class="col-md-6 col-md-offset-3 jumbotron">
            <div class="text-center">
                <h1>{% block header_text %}{% endblock %}</h1>
                <form method="POST" action="{% block form_action %}{% endblock %}">
                    {{ form.text }}
                    {% csrf_token %}
                    {% if form.errors %}
                    <div class="form-group has-error">
                        <span class="help-block">{{ form.text.errors }}</span>
                    </div>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            {% block table %}
            {% endblock %}
        </div>
    </div>
</div>
<script src="http://code.jquery.com/jquery.min.js"></script>
<script src="/static/list.js"></script>
</body>
</html>

lists/templates/home.html
{% extends 'base.html' %}
{% block header_text %}작업 목록 시작{% endblock %}
{% block form_action %}{% url 'new_list' %}{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}
{% block header_text %}Your To-Do list{% endblock %}
{% block form_action %}{% url 'view_list' list.id%}{% endblock %}
{% block table %}
<table id="id_list_table" class="table">
    {% for item in list.item_set.all %}
    <tr>
        <td>{{ forloop.counter }}: {{ item.text }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

tasks/templates/home.html
<html>
	<head>
		<title>Pomodoro web</title>
	</head>
	<body>
		<h1>To-Do</h1>
		<form method="POST">
			<input name="task_title" id="id_new_task" placeholder='The task to do'/>
			{% csrf_token %}
		</form>
		<table id="id_list_table">
			{% for task in tasks %}
			<tr><td>{{ forloop.counter }}: {{ task.title }}</td></tr>
			{% endfor %}
		</table>
	</body>
</html>